apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  namespace: cep-project1
  labels:
    app: wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.52.161
    # Exported path of NFS server - NFS server IP above
    path: "/mydbdata"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: cep-project1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi